### ISSUE TITLE
Readme setup instructions typo

### ISSUE THREAD

**Issue by drmingdrmer** [4383/notebooks#1]
It should be `install -r requirements.txt`. A missing `-r`:

```
$ git clone https://github.com/4383/notebooks
$ cd notebooks
$ python -m virtualenv .
$ source bin/activate
$ python -m pip install requirements.txt
$ jupyter notebook
```

**Comment by 4383** [comment]
@drmingdrmer good catch!

Thanks I'll fix it

**Comment by 4383** [comment]
Fixed by https://github.com/4383/notebooks/commit/39bb28613551244cb0ca79d43e5b1af2d674f2f6

Thanks @drmingdrmer
